---
title: "Grossepieper_Nils_Assignment04"
author: "Nils Grossepieper"
date: "2023-03-27"
output: html_document
---

(1) In the folder data you will find the original images. Each image is labeled as either pizza or no pizza.
Apply the pipeline below and export to csv.

```{r, warning=FALSE, message=FALSE}

# Get the image directory:
image_directory <- "C:/Users/gross/OneDrive/Dokumente/imgs/training"

# pipeline template R
library(tidyverse)
library(OpenImageR)

# define the pipeline
pipeline <- function(img) {
  img %>%
    resizeImage(200, 200, method = "bilinear") %>%
    rgb_2gray() %>%
    HOG(cells = 10, orientations = 9)
}

preprocess <- function(image_directory, auto_labels = T) {
  # list all images in the folder
  files <- list.files(image_directory,
                      pattern = "*.jpg", full.names = T)
  # read all images
  images <- map(files, readImage)
  # apply the pipeline to each image
  preprocessed <- map(images, pipeline)
  # stack the list in a matrix
  preprocessed_matrix <- matrix(unlist(preprocessed),
                                ncol = 900, byrow = TRUE)
  if(auto_labels) {
    # infer labels from file names
    preprocessed_matrix <- cbind(str_extract(files, "(not_)*pizza"),
                                 preprocessed_matrix)
  }
  # return the matrix
  return(preprocessed_matrix)
}

# Run the functions:
image_data <- preprocess(image_directory)

# Export image_data to as csv file:
library(MASS)
write.matrix(image_data, sep = ",",
             file = "C:/Users/gross/OneDrive/Dokumente/Grossepieper_Nils_Assignment04/pizza_data_R.csv")

```

(2) Print the shape (i.e., dimension) of the preprocessed result.

```{r}

# Print the dimension of the reprocessed result:
dim(image_data)

# or do it in two steps
nrow(image_data)
ncol(image_data)

# The matrix image_data has 1966 rows and 901 columns.

```

(3) Print the top-left 5x5 submatrix of the result.

```{r}

# Print the top left 5x5 sub matrix of the image_data matrix:
submatrx_of_image_data <- image_data[1:5, 1:5]
submatrx_of_image_data

```




